Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-069aabeee6f53e7bf
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, inst, from, cloud, formation]]
