Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-069aabeee6f53e7bf
      Tags:
        - Key: "Name"
          Value: !Join
            - " "
            - - "My Instance In"
              - !Ref AWS::Region
      SecurityGroups:
        - !Ref FormSG
  FormSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: FormSG
      GroupDescription: Allow ssh and http to conenct to host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Form
